//this was generated by claude for seeding 

import { connectDB, getDB } from '../db/connection.js';

var categories = ['Outdoors', 'Food', 'Games', 'Music', 'Fitness', 'Art', 'Books', 'Tech', 'Movies', 'Community'];

var titleWords = [
  'Sunset Hike', 'Board Game Night', 'Trivia Meetup', 'Community Potluck', 'Morning Run Club',
  'Open Mic Night', 'Farmers Market Walk', 'Book Swap', 'Beach Cleanup', 'Pickup Basketball',
  'Movie Marathon', 'Painting Workshop', 'Coffee and Chat', 'Bike Ride', 'Photography Walk',
  'Karaoke Night', 'Yoga in the Park', 'Cooking Class', 'Chess Club', 'Kayaking Trip',
  'Live Music Night', 'Puzzle Swap', 'Dog Park Meetup', 'Garden Volunteering', 'Study Group',
  'Rooftop Hangout', 'Craft Fair', 'Wine Tasting', 'Bonfire Night', 'Ultimate Frisbee'
];

var descriptions = [
  'Come join us for a fun and casual time, all skill levels welcome!',
  'Looking to meet new people who share this interest. Bring a friend!',
  'We do this every so often and always have a great turnout.',
  'Bring your own supplies if you have them, extras will be available too.',
  'First time doing this one, should be a blast. RSVP if you can make it.',
  'Weather permitting, we will move indoors if needed.',
  'Family friendly and beginner friendly. No experience necessary.',
  'Snacks and drinks provided. Just bring good vibes.',
  'This is a recurring meetup, but newcomers are always welcome.',
  'Let us know in the comments if you are bringing anyone else along.'
];

var firstNames = [
  'alex', 'jordan', 'taylor', 'morgan', 'casey', 'riley', 'jamie', 'avery', 'quinn', 'rowan',
  'sam', 'drew', 'skyler', 'cameron', 'reese', 'emerson', 'finley', 'harper', 'kai', 'logan'
];

var lastWords = [
  'maine', 'portland', 'pine', 'harbor', 'coast', 'ocean', 'trail', 'oak', 'fox', 'wren',
  '207', 'tide', 'birch', 'granite', 'moss', 'cliff', 'sea', 'north', 'cove', 'reed'
];

var commentTexts = [
  'Sounds fun, count me in!',
  'What should I bring?',
  'Is this beginner friendly?',
  'Can I bring a plus one?',
  'Looking forward to this!',
  'What time should we actually show up?',
  'Is parking available nearby?',
  'This was so much fun last time, excited for round two.',
  'Do we need to sign up in advance?',
  'Perfect timing, I was just looking for something like this.',
  'Will there be food?',
  'Hope the weather holds up!',
  'Thanks for organizing this.',
  'Never done this before, a little nervous but excited.',
  'See everyone there!'
];

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomDate() {
  var month = randomInt(7, 12);
  var day = randomInt(1, 28);
  var monthStr = month < 10 ? '0' + month : '' + month;
  var dayStr = day < 10 ? '0' + day : '' + day;
  return '2026-' + monthStr + '-' + dayStr;
}

function randomTime() {
  var hour = randomInt(8, 20);
  var minute = randomItem(['00', '15', '30', '45']);
  var hourStr = hour < 10 ? '0' + hour : '' + hour;
  return hourStr + ':' + minute;
}

function randomPastDate() {
  var date = new Date();
  date.setDate(date.getDate() - randomInt(0, 60));
  return date;
}

async function seed() {
  await connectDB();
  var db = getDB();

  console.log('Clearing existing collections...');
  await db.collection('users').deleteMany({});
  await db.collection('posts').deleteMany({});
  await db.collection('comments').deleteMany({});
  await db.collection('meetups').deleteMany({});

  // ---- users: 50 ----
  console.log('Seeding users...');
  var users = [];
  var usedNames = {};
  for (var i = 0; i < 50; i++) {
    var uname;
    do {
      uname = randomItem(firstNames) + randomItem(lastWords) + i;
    } while (usedNames[uname]);
    usedNames[uname] = true;

    users.push({ username: uname, password: 'password123' });
  }
  var userResult = await db.collection('users').insertMany(users);
  var usernames = users.map(function(u) { return u.username; });

  // ---- posts: 200 ----
  console.log('Seeding posts...');
  var posts = [];
  for (var i = 0; i < 200; i++) {
    posts.push({
      title: randomItem(titleWords),
      description: randomItem(descriptions),
      category: randomItem(categories),
      eventDate: randomDate(),
      eventTime: randomTime(),
      username: randomItem(usernames)
    });
  }
  var postResult = await db.collection('posts').insertMany(posts);
  var postIds = Object.values(postResult.insertedIds);

  // ---- comments: 550 ----
  console.log('Seeding comments...');
  var comments = [];
  for (var i = 0; i < 550; i++) {
    comments.push({
      postId: randomItem(postIds),
      username: randomItem(usernames),
      text: randomItem(commentTexts),
      createdAt: randomPastDate()
    });
  }
  await db.collection('comments').insertMany(comments);

  // ---- meetups: 200, no duplicate postId+username pairs ----
  console.log('Seeding meetups...');
  var meetups = [];
  var seenPairs = {};
  var attempts = 0;

  while (meetups.length < 200 && attempts < 5000) {
    attempts++;
    var postId = randomItem(postIds);
    var username = randomItem(usernames);
    var pairKey = postId.toString() + '_' + username;

    if (seenPairs[pairKey]) {
      continue;
    }
    seenPairs[pairKey] = true;

    meetups.push({ postId: postId, username: username, joinedAt: randomPastDate() });
  }
  await db.collection('meetups').insertMany(meetups);

  var total = users.length + posts.length + comments.length + meetups.length;
  console.log('Done! Inserted ' + users.length + ' users, ' + posts.length + ' posts, ' + comments.length + ' comments, ' + meetups.length + ' meetups.');
  console.log('Total records: ' + total);

  process.exit(0);
}

seed();